# Generated by Django 3.2.5 on 2021-07-29 11:28

import commonknowledge.wagtail.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('stopwatch', '0004_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('searchable', models.BooleanField(default=False)),
                ('newsflash', models.BooleanField(default=False)),
                ('style', models.CharField(choices=[('COMPACT', 'Compact'), ('EXPANDED', 'Expanded')], default='COMPACT', max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=(commonknowledge.wagtail.models.ChildListMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ExternalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('target_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_description', models.CharField(default='', max_length=512)),
                ('landing_video', models.URLField(blank=True, null=True)),
                ('body', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('articles_list', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('site_area', wagtail.core.blocks.PageChooserBlock(page_type=['stopwatch.Article']))])), ('cta', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('target', wagtail.core.blocks.PageChooserBlock(required=False))])), ('tabs', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('tabs', wagtail.core.blocks.StreamBlock([('stats', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.ChoiceBlock(choices=[('chat-left', 'Speech Bubble'), ('grap-up', 'Graph'), ('hammer', 'Gavel')], template='widgets/icon_block.html')), ('short_title', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('call_to_action', wagtail.core.blocks.CharBlock(required=False)), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('info', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.ChoiceBlock(choices=[('chat-left', 'Speech Bubble'), ('grap-up', 'Graph'), ('hammer', 'Gavel')], template='widgets/icon_block.html')), ('short_title', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('call_to_action', wagtail.core.blocks.CharBlock(required=False)), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('author', wagtail.snippets.blocks.SnippetChooserBlock('stopwatch.StaffMember', required=False))]))]))])), ('newsletter_signup', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('target', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('import_ref', models.IntegerField(blank=True, null=True)),
                ('intro_text', models.CharField(blank=True, default='', max_length=1024)),
                ('summary', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True)),
                ('body', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('articles_list', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('site_area', wagtail.core.blocks.PageChooserBlock(page_type=['stopwatch.Article']))])), ('cta', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('target', wagtail.core.blocks.PageChooserBlock(required=False))])), ('tabs', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('tabs', wagtail.core.blocks.StreamBlock([('stats', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.ChoiceBlock(choices=[('chat-left', 'Speech Bubble'), ('grap-up', 'Graph'), ('hammer', 'Gavel')], template='widgets/icon_block.html')), ('short_title', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('call_to_action', wagtail.core.blocks.CharBlock(required=False)), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('info', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.ChoiceBlock(choices=[('chat-left', 'Speech Bubble'), ('grap-up', 'Graph'), ('hammer', 'Gavel')], template='widgets/icon_block.html')), ('short_title', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('call_to_action', wagtail.core.blocks.CharBlock(required=False)), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('author', wagtail.snippets.blocks.SnippetChooserBlock('stopwatch.StaffMember', required=False))]))]))])), ('newsletter_signup', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('target', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stopwatch.stopwatchimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
