# Generated by Django 3.2.6 on 2021-08-17 16:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('stopwatch', '0010_auto_20210817_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL', null=True)),
                ('instagram', models.CharField(blank=True, help_text='Your Instagram username, without the @', max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Your Twitter username, without the @', max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True)),
                ('standard_donation_request', wagtail.core.fields.RichTextField(default='We aim to address excess and disproportionate stop and search, promote best practice and ensure fair, effective policing for all.')),
                ('standard_mailinglist_request', wagtail.core.fields.RichTextField(default='Regular updates on our activities, noteworthy articles, and how you can get involved in our work.')),
                ('tagline', wagtail.core.fields.RichTextField(default='', help_text='Text displayed at the base of a site')),
                ('tagline_long', wagtail.core.fields.RichTextField(default='<strong>StopWatch</strong> is a coalition of legal experts, academics, citizens and civil liberties campaigners. We aim to address excess and disproportionate stop and search, promote best practice and ensure fair, effective policing for all.', help_text='Text displayed at the base of pages')),
                ('donation_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
