# Generated by Django 3.2.6 on 2021-08-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0012_auto_20210819_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='landing_video',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stopwatch.stopwatchimage'),
        ),
    ]
