# Generated by Django 3.2.6 on 2021-08-24 08:19

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0015_auto_20210823_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='youtube',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_description',
            field=models.CharField(default='Research and action fof fair and accountable policing', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bottom_page_links',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())]))], blank=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='tabs',
            field=wagtail.core.fields.StreamField([('tab', wagtail.core.blocks.StructBlock([('site_area', wagtail.core.blocks.PageChooserBlock()), ('featured_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('cta', wagtail.core.blocks.CharBlock(required=False))]))], blank=True),
        ),
    ]
