# Generated by Django 3.2.6 on 2021-08-24 11:15

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0016_auto_20210824_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='donation_page',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='2 Langley Lane London SW8 1GB', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_contact',
            field=models.EmailField(default='info@stop-watch.org', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='end_matter',
            field=models.TextField(default='Registered Charity No: 1161908'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(default='+44 (0)208 226 5737', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bottom_page_links',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('label', wagtail.core.blocks.CharBlock(required=False))]))], blank=True),
        ),
    ]
