# Generated by Django 3.2.6 on 2021-08-26 12:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0018_auto_20210824_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stopwatch.stopwatchimage'),
        ),
    ]
