# Generated by Django 3.2.6 on 2021-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0023_alter_organisation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website_text',
            field=models.CharField(max_length=1024),
        ),
    ]
