# Generated by Django 3.2.6 on 2021-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0027_auto_20210903_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hide_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='hide_related_articles',
            field=models.BooleanField(default=False),
        ),
    ]
