# Generated by Django 3.2.6 on 2021-09-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0028_auto_20210903_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='post_newsletter_page',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_list_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
