# Generated by Django 3.2.7 on 2021-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0031_auto_20210906_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externalpage',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
    ]
