# Generated by Django 3.2.7 on 2021-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0031_auto_20210906_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_ua',
            field=models.TextField(help_text='Google Analytics UA', null=True),
        ),
    ]
