# Generated by Django 3.2.7 on 2021-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0032_sitesettings_google_analytics_ua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_ua',
            field=models.TextField(blank=True, help_text='Google Analytics UA, to allow setting up Google Analytics', null=True, verbose_name='Google Analytics UA'),
        ),
    ]
