# Generated by Django 3.2.7 on 2021-09-09 11:44

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0032_auto_20210909_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hide_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hide_related_articles',
        ),
        migrations.AddField(
            model_name='category',
            name='hide_dates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='hide_related_articles',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='tabs',
            field=wagtail.core.fields.StreamField([('tab', wagtail.core.blocks.StructBlock([('site_area', wagtail.core.blocks.PageChooserBlock()), ('featured_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(label='Detail heading', required=False)), ('description', wagtail.core.blocks.TextBlock(label='Detail description', required=False)), ('cta', wagtail.core.blocks.CharBlock(label='Call to action text', required=False))]))], blank=True),
        ),
    ]
