# Generated by Django 3.2.7 on 2021-09-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0033_auto_20210909_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stopwatch.stopwatchimage', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='form',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stopwatch.stopwatchimage', verbose_name='Search image'),
        ),
    ]
