# Generated by Django 3.2.7 on 2021-09-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0033_alter_sitesettings_google_analytics_ua'),
        ('stopwatch', '0034_auto_20210909_1418'),
    ]

    operations = [
    ]
