# Generated by Django 3.2.7 on 2022-10-04 16:00

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0038_auto_20221004_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedarticles',
            name='related_article',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_relations', to='stopwatch.article'),
        ),
    ]
