# Generated by Django 3.2.7 on 2023-06-01 14:12

from django.db import migrations
import stopwatch.models.components
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0040_auto_20230530_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontentpage',
            name='summary',
            field=wagtail.core.fields.StreamField([('text', stopwatch.models.components.SummaryTextBlock())], blank=True, help_text='Summary text to be displayed in articles listing page'),
        ),
    ]
