# Generated by Django 3.2.23 on 2024-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0049_auto_20240820_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_mode',
            field=models.CharField(choices=[('articles', 'Display all articles'), ('sections', 'Display chosen articles')], default='articles', max_length=20),
        ),
    ]
