# Generated by Django 3.2.23 on 2024-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0052_alter_categorychildpagesection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorychildpagesection',
            name='style',
            field=models.CharField(choices=[('GRID', 'Grid'), ('ROWS', 'Rows')], default='GRID', max_length=128),
        ),
    ]
