# Generated by Django 3.2.23 on 2024-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0053_categorychildpagesection_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_filters',
            field=models.BooleanField(default=True, help_text='Display filters on page when display mode is articles'),
        ),
    ]
