# Generated by Django 3.2.6 on 2021-08-16 10:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210816_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.core.blocks.StructBlock([('embed_url', wagtail.core.blocks.URLBlock())])), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('cta', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(required=False)), ('target', wagtail.core.blocks.PageChooserBlock(required=True))])), ('newsletter_signup', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(required=False)), ('target', wagtail.core.blocks.PageChooserBlock(required=True))]))], verbose_name='Event details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='intro_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', max_length=1024),
        ),
    ]
