# Generated by Django 3.2.6 on 2021-09-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0030_auto_20210906_1513'),
        ('projects', '0010_auto_20210903_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stopwatch.stopwatchimage', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='eventtheme',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stopwatch.stopwatchimage', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='project',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stopwatch.stopwatchimage', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='projectarticle',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stopwatch.stopwatchimage', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='projectevents',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stopwatch.stopwatchimage', verbose_name='Search image'),
        ),
    ]
