# Generated by Django 3.2.7 on 2021-09-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0032_auto_20210909_1049'),
        ('projects', '0011_auto_20210906_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventtheme',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectarticle',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectevents',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stopwatch.stopwatchimage'),
        ),
        migrations.AddField(
            model_name='projectevents',
            name='show_header_image',
            field=models.BooleanField(default=True),
        ),
    ]
