databases:
  - engine: PG
    name: db
    version: "12"
domains:
  - domain: stopwatch.commonknowledge.dev
    type: PRIMARY
envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: EV[1:nqAWJXElIRuXUIta/nm3SFIXDAAFRaY0:Fxf2ZZ+zc5G/Mym1dGkUiPwz/hJbD3HyAtWXzhOtWeQkrTX1g+ytZ3f/YHcpcNsnt7tST91Wav3VwILS0wPmfCswhW0Rqqwb3H+e9aBO7aE=]
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    value: EV[1:UODShe2skLp0NgK9aOOCeYX2RlJpJSwM:/W+ErZde+9JjvwVUcEClCKFHa0JukYCZX27rJ48br+uXfaV/35DlyESGvuYThYPmglItC8mLLHl0UgY=]
  - key: MAILGUN_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: EV[1:rWtVG/LT8IzgUhRORiFSHxvzgahml62Y:ssG1hhzZgGvvCTFcT8C2Exey5EgCRyYv3zbgfp0xAVNYwWu8nmBXs7MH+pvUOdBMw26EPumQjrPQI6N6AMjghbqs]
  - key: WAGTAILADMIN_BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${_self.PUBLIC_URL}
  - key: AWS_S3_REGION_NAME
    scope: RUN_AND_BUILD_TIME
    value: ams3
  - key: AWS_STORAGE_BUCKET_NAME
    scope: RUN_AND_BUILD_TIME
    value: stopwatch
  - key: AWS_S3_CUSTOM_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: https://stopwatch.ams3.cdn.digitaloceanspaces.com
  - key: AWS_S3_ENDPOINT_URL
    scope: RUN_AND_BUILD_TIME
    value: https://ams3.digitaloceanspaces.com
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
    value: OQPXF34TDQBI7HARX6DE
  - key: MEDIA_URL
    scope: RUN_AND_BUILD_TIME
    value: https://stopwatch.ams3.cdn.digitaloceanspaces.com/
  - key: MAILGUN_API_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.eu.mailgun.net/v3
  - key: MAILGUN_SENDER_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: commonknowledge.dev
jobs:
  - dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: commonknowledge/stopwatch
    instance_count: 1
    instance_size_slug: basic-xs
    kind: PRE_DEPLOY
    name: release
    run_command: pipenv run bash .bin/release.sh
name: stopwatch
region: ams
services:
  - dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: commonknowledge/stopwatch
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    name: server
    routes:
      - path: /
    run_command: pipenv run gunicorn --worker-tmp-dir /dev/shm stopwatch.wsgi
static_sites:
  - dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: commonknowledge/stopwatch
    name: staticfiles
    output_dir: /app/static
    routes:
      - path: /static
