# Generated by Django 3.2.5 on 2021-07-28 08:56

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_listpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpage',
            name='landing_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listpage',
            name='page_description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='body',
            field=wagtail.core.fields.StreamField([('articles_list', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('site_area', wagtail.core.blocks.PageChooserBlock(page_type=['home.ListPage']))])), ('cta', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('target', wagtail.core.blocks.PageChooserBlock(required=False))])), ('tabs', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('tabs', wagtail.core.blocks.StreamBlock([('stats', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.ChoiceBlock(choices=[('chat-left', 'Speech Bubble'), ('grap-up', 'Graph'), ('hammer', 'Gavel')], template='widgets/icon_block.html')), ('short_title', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('call_to_action', wagtail.core.blocks.CharBlock(required=False)), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('info', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.ChoiceBlock(choices=[('chat-left', 'Speech Bubble'), ('grap-up', 'Graph'), ('hammer', 'Gavel')], template='widgets/icon_block.html')), ('short_title', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('call_to_action', wagtail.core.blocks.CharBlock(required=False)), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('author', wagtail.snippets.blocks.SnippetChooserBlock('stopwatch.StaffMember', required=False))]))]))])), ('newsletter_signup', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('target', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True),
        ),
    ]
