# Generated by Django 3.2.5 on 2021-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_homepage_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpage',
            name='newsflash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listpage',
            name='searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listpage',
            name='style',
            field=models.CharField(choices=[('COMPACT', 'Compact'), ('EXPANDED', 'Expanded')], default='COMPACT', max_length=128),
        ),
    ]
